### ISSUE TITLE
completion misbehaves on spaces

### ISSUE THREAD

**Issue by isaacl** [moshen/open-bash-completion#1]
1) create file "test 1.txt"
2) type "open t<Tab>"

Completion is: "1.txt  t/     test"

**Comment by isaacl** [comment]
Thanks very much for the quick fix. You might need quotes around those variables, not sure.

**Comment by moshen** [comment]
No problem :beers:

Your comment made me realize that I messed up my fix commit as well.  Since `$IFS` is the internal bash word boundary delimiter, I have a hard time seeing why someone would do something silly like reset it to something that would break on whitespace... but you never know... so I quoted it.

**Comment by isaacl** [comment]
Fix looks good, thanks. tested with spaces and backslashes.
